backend:
  name: github
  repo: AtiqKhan95/docusuarus-pages
  branch: main

media:
  input: static/img
  output: /img
  path: static/img
  extensions: [jpg, jpeg, png, gif, svg]
  categories: [image]

content:
  - name: "blog"
    label: "Blog Posts"
    type: collection
    path: blog
    format: yaml-frontmatter
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Publish Date", name: "date", type: "date" }
      - { label: "Featured Image", name: "thumbnail", type: "image", required: false }
      - { label: "Body", name: "body", type: "rich-text" }
      - { label: "Tags", name: "tags", type: "string", list: true, required: false }
      - { label: "Author", name: "author", type: "string", required: false }
    view:
      fields: [title, date, author]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

  - name: "docs"
    label: "Documentation"
    type: collection
    path: docs
    format: yaml-frontmatter
    subfolders: true
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Body", name: "body", type: "rich-text" }
      - { label: "Order", name: "sidebar_position", type: "number", required: false }
      - { label: "Description", name: "description", type: "text", required: false }
    view:
      fields: [title, sidebar_position]
      primary: title
      sort: [sidebar_position, title]
      search: [title, description]

  - name: "config"
    label: "Site Configuration"
    type: file
    path: docusaurus.config.ts
    fields:
      - { label: "Site Title", name: "title", type: "string" }
      - { label: "Site Tagline", name: "tagline", type: "string" }
      - { label: "Site Description", name: "description", type: "text", required: false }
      - { label: "GitHub URL", name: "githubUrl", type: "string", required: false }
      - { label: "Twitter URL", name: "twitterUrl", type: "string", required: false }
      - { label: "Discord URL", name: "discordUrl", type: "string", required: false }
