repositories:
  - name: "Main Docusaurus"
    repo: "AtiqKhan95/docusuarus-pages"
    path: "/"

  - name: "Decisions"
    repo: "AtiqKhan95/decisions-replica"
    path: "/"

media:
  - name: "Main Images"
    repository: "Main Docusaurus"
    input: "static/img"
    output: "/img"
    extensions: [jpg, jpeg, png, gif, svg]
    
  - name: "Decisions assets"
    repository: "Decisions"
    input: "bdr/images"
    output: "/decision_screenshots"
    extensions: [jpg, jpeg, png, gif, svg]

content:
  - name: "blog"
    repository: "Main Docusaurus"
    label: "Blog Posts"
    type: collection
    path: blog
    format: yaml-frontmatter
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Publish Date", name: "date", type: "date" }
      - { label: "Featured Image", name: "thumbnail", type: "image", required: false }
      - { label: "Body", name: "body", type: "rich-text" }
      - { label: "Tags", name: "tags", type: "string", list: true, required: false }

  - name: "docs"
    repository: "Main Docusaurus"
    label: "Documentation"
    type: collection
    path: docs
    format: yaml-frontmatter
    subfolders: true
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Body", name: "body", type: "rich-text" }
      - { label: "Order", name: "sidebar_position", type: "number", required: false }
      - { label: "Description", name: "description", type: "text", required: false }
    view:
      fields: [title, sidebar_position]
      primary: title
      sort: [sidebar_position, title]
      search: [title, description]
    exclude: ["README.md"]

  - name: "config"
    label: "Site Configuration"
    type: file
    path: docusaurus.config.ts
    fields:
      - { label: "Site Title", name: "title", type: "string" }
      - { label: "Site Tagline", name: "tagline", type: "string" }
      - { label: "Site Description", name: "description", type: "text", required: false }
      - { label: "GitHub URL", name: "githubUrl", type: "string", required: false }
      - { label: "Twitter URL", name: "twitterUrl", type: "string", required: false }
      - { label: "Discord URL", name: "discordUrl", type: "string", required: false }
      
  - name: "Decisions"
    repository: "Decisions"
    label: "Decisions"
    type: collection
    path: guides
    format: yaml-frontmatter
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Body", name: "body", type: "rich-text" }
      - { label: "Order", name: "sidebar_position", type: "number", required: false }
      - { label: "Description", name: "description", type: "text", required: false }
    view:
      fields: [title, sidebar_position]
      primary: title
      sort: [sidebar_position, title]
      search: [title, description]
    exclude: ["README.md"]